### ISSUE TITLE
Missing Copy function in QR Scanner

### ISSUE THREAD

**Issue by brauncg** [Koizeay/Toolbox#4]
There’s no copy function in the QR scanner. Not all QR codes are URL links. And even with URLs I’d prefer to copy rather than open in a default browser. Please consider adding a Copy option. Thank you.

**Comment by Koizeay** [comment]
Hello,

As this feature is a good idea, it has been added with [this commit](https://github.com/Koizeay/Toolbox/commit/94db434a36e5a65fb77e6769c3d8e5b07cc3db56) and will be available in a future app update.

This new feature adds a "Copy" button allowing user to copy the content shown into the dialog when scanning a text or URL QR code via the "QR reader" tool.

_This issue will be closed as it has been implemented and will be available to users in a future app update._
